apiVersion: v1
kind: ConfigMap
metadata: {name: {{ include "leo.name" . }} }
data:
  LEO_HTTP_ADDR: ":8080"
  LEO_DATABASE_URL: {{ .Values.config.databaseURL | quote }}
  LEO_REDIS_ADDR: {{ .Values.config.redisAddr | quote }}
  LEO_REDIS_PASSWORD: {{ .Values.config.redisPassword | quote }}
  LEO_PUBLIC_BASE_URL: {{ .Values.config.publicBaseURL | quote }}
  LEO_SCHEMA_VERSION: {{ .Values.config.schemaVersion | quote }}
  LEO_COOKIE_SECURE: "true"
