apiVersion: v1
kind: Secret
metadata: {name: {{ include "leo.name" . }} }
type: Opaque
stringData:
  LEO_MASTER_KEY: {{ .Values.secret.masterKey | quote }}
  LEO_ADMIN_USERNAME: {{ .Values.secret.adminUsername | quote }}
  LEO_ADMIN_PASSWORD: {{ .Values.secret.adminPassword | quote }}
