apiVersion: v1
kind: Service
metadata: {name: {{ include "leo.name" . }}}
spec:
  selector: {app: {{ include "leo.name" . }}, component: api}
  ports: [{name: http, port: {{ .Values.service.port }}, targetPort: http}]
